export const MATCHED_KEYWORDS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Node.js',
  'REST APIs',
  'JWT',
  'Docker',
  'Data Structures',
  'Algorithms',
  'System Design',
  'Microservices',
  'Serverless Architecture',
  'Communication',
  'Collaboration',
  'Problem-solving',
  'State Management Libraries',
  'E2E Testing',
  'Production Monitoring',
  'Performance Optimization',
  'OAuth2',
];

export const MISSING_KEYWORDS = [
  'AWS Lambda',
  'DynamoDB',
  'React Hooks',
  'Context API',
  'Jest',
  'Cypress',
  'AWS API Gateway',
  'AWS S3',
  'CloudWatch',
  'Datadog',
  'GitHub Actions',
  'Mentoring',
  'Design Review Participation',
];
