import { useState, useEffect, useRef } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { getAnalysis } from '../api/analysis';
import { endInterview, getSession, type EndRequest, type SessionResponse, type TurnFeedback } from '../api/interview';
import { isInterviewQuestionTurn } from '../utils/interviewQuestions';
import { clearInterviewPointer } from '../utils/interviewPointer';
import { useAuth } from '../auth/AuthContext';
import { SignupPromptModal } from '../components/SignupPromptModal';
import { SAMPLE_INTERVIEW_SESSION, SAMPLE_INTERVIEW_SESSION_ID } from '../types/sampleInterviewSession';
import './InterviewResults.css';

type InterviewType = 'behavioral' | 'technical';
type TranscriptTurn = SessionResponse['conversation'][number];
type PendingInterviewFinalization = {
  endReason: EndRequest['endReason'];
  startedAt: number;
};

/** One interviewer question plus the candidate turns that answered it. */
type TranscriptGroup = {
  question: TranscriptTurn | null;
  answers: TranscriptTurn[];
};

const FINALIZATION_STORAGE_PREFIX = 'resumematch_interview_finalizing_';
const FINALIZATION_TTL_MS = 2 * 60 * 1000;
const ASSESSMENT_POLL_INTERVAL_MS = 2000;
const ASSESSMENT_POLL_MAX_ATTEMPTS = 30;
const ASSESSMENT_END_RETRY_DELAY_MS = 3000;
const ASSESSMENT_END_MAX_ATTEMPTS = 3;
const COPIED_RESET_MS = 1600;
/** Breathing room between the sticky tab bar and the panel heading it scrolls to. */
const TAB_SCROLL_GAP = 12;

/* The two rubrics score on different dimensions, so the "Show details" callout
   has to name the right five — quoting the behavioral weights on a technical
   session would state weights that were never applied. */
const ASSESSMENT_RUBRIC_COPY: Record<InterviewType, string> = {
  behavioral:
    'Scores are generated by grading the full transcript against five weighted dimensions. '
    + 'The overall score is the weighted average — Communication Structure (20%), STAR Framework '
    + 'Usage (25%), Specificity & Metrics (25%), Role Relevance (20%), and Self-Awareness (10%). '
    + 'This is guidance to help you prepare, not a hiring decision.',
  technical:
    'Scores grade the full transcript against 5 weighted dimensions. The overall score is their '
    + 'weighted average — Technical Accuracy (25%), Problem Solving Approach (25%), Communication '
    + 'Clarity (20%), Depth of Knowledge (20%), Practical Experience (10%). This is guidance to '
    + 'help you prepare, not a hiring decision.',
};

function getFinalizationStorageKey(sessionId: string): string {
  return `${FINALIZATION_STORAGE_PREFIX}${sessionId}`;
}

function loadPendingInterviewFinalization(sessionId: string): PendingInterviewFinalization | null {
  try {
    const raw = sessionStorage.getItem(getFinalizationStorageKey(sessionId));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<PendingInterviewFinalization>;
    const endReason = parsed.endReason;
    const startedAt = parsed.startedAt;
    const isValidReason = endReason === 'timer_expired'
      || endReason === 'user_ended'
      || endReason === 'all_questions_answered';
    const isFresh = typeof startedAt === 'number'
      && Date.now() - startedAt <= FINALIZATION_TTL_MS;
    if (!isValidReason || !isFresh || typeof startedAt !== 'number') {
      sessionStorage.removeItem(getFinalizationStorageKey(sessionId));
      return null;
    }
    return { endReason, startedAt };
  } catch {
    return null;
  }
}

function savePendingInterviewFinalization(sessionId: string, endReason: EndRequest['endReason']): void {
  try {
    sessionStorage.setItem(
      getFinalizationStorageKey(sessionId),
      JSON.stringify({ endReason, startedAt: Date.now() })
    );
  } catch {
    // Session storage can be unavailable in restricted browser contexts.
  }
}

function clearPendingInterviewFinalization(sessionId: string): void {
  try {
    sessionStorage.removeItem(getFinalizationStorageKey(sessionId));
  } catch {
    // Session storage can be unavailable in restricted browser contexts.
  }
}

function formatDuration(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = secs % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatTime(dateStr: string): string {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

function scoreColor(score: number): string {
  if (score >= 80) return 'var(--score-high)';
  if (score >= 60) return 'var(--score-good)';
  return 'var(--score-mid)';
}

function formatInterviewType(type: string): string {
  if (!type) return 'Interview';
  return type.charAt(0).toUpperCase() + type.slice(1);
}

function normalizeJobTitle(title: string): string {
  return title.replace(/\s+@\s+/, ' — ');
}

function getSessionTitle(session: SessionResponse): string {
  if (session.roleName && session.companyName) {
    return `${session.roleName} — ${session.companyName}`;
  }
  if (session.roleName) return session.roleName;
  if (session.jobTitle) return normalizeJobTitle(session.jobTitle);
  return `${formatInterviewType(session.interviewType)} Practice Session (No job selected)`;
}

/** Role / company split so the heading can render the em dash as its own token. */
function getSessionHeading(session: SessionResponse): { role: string; company: string | null } {
  if (session.roleName && session.companyName) {
    return { role: session.roleName, company: session.companyName };
  }
  return { role: getSessionTitle(session), company: null };
}

function parseMatchScore(score?: number | string): number | null {
  if (score == null || (typeof score === 'string' && score.trim() === '')) return null;
  const numeric = typeof score === 'number' ? score : Number(score);
  if (!Number.isFinite(numeric)) return null;
  return Math.round(numeric);
}

function formatMatchScore(score?: number | string): string | null {
  const numeric = parseMatchScore(score);
  return numeric == null ? null : `${numeric}% Match`;
}

function getMatchScoreTier(score: number): 'high' | 'good' | 'mid' | 'low' | 'poor' {
  if (score >= 86) return 'high';
  if (score >= 76) return 'good';
  if (score >= 61) return 'mid';
  if (score >= 41) return 'low';
  return 'poor';
}

function formatCategoryWeight(weight: number): string {
  const normalized = weight > 0 && weight <= 1 ? weight * 100 : weight;
  return `${Number.isInteger(normalized) ? normalized : Number(normalized.toFixed(1))}`;
}

function getResumeLabel(session: SessionResponse): string {
  return session.fileName || 'Default Resume';
}

function getInterviewType(type: string): InterviewType {
  return type === 'technical' ? 'technical' : 'behavioral';
}

function getJobTitle(session: SessionResponse): string | undefined {
  if (session.roleName && session.companyName) return `${session.roleName} @ ${session.companyName}`;
  return session.roleName || session.jobTitle;
}

function getTranscriptLabel(turn: TranscriptTurn, uppercase = false): string {
  const label = turn.role === 'interviewer' ? 'Interviewer' : 'You';
  return uppercase ? label.toUpperCase() : label;
}

function isCandidateTurn(turn: TranscriptTurn): boolean {
  return turn.role === 'user' || turn.role === 'candidate';
}

/** The bundle renders one block per question, so pair each interviewer turn with
    the candidate turns that follow it. A stray answer with no preceding question
    (malformed/legacy rows) still gets its own block rather than being dropped. */
function groupTranscript(conversation: TranscriptTurn[]): TranscriptGroup[] {
  const groups: TranscriptGroup[] = [];
  for (const turn of conversation) {
    if (turn.role === 'interviewer') {
      groups.push({ question: turn, answers: [] });
      continue;
    }
    const current = groups[groups.length - 1];
    if (!current) {
      groups.push({ question: null, answers: [turn] });
    } else {
      // Consecutive candidate turns belong to the question above them — starting
      // a new group here would emit a second bare "YOU" header with no question.
      current.answers.push(turn);
    }
  }
  return groups;
}

/** Split a transcript turn into display paragraphs. */
function toParagraphs(content: string): string[] {
  const parts = content.split(/\n\s*\n|\n/).map(part => part.trim()).filter(Boolean);
  return parts.length ? parts : [content];
}

function formatFillerWords(fillerWords?: Record<string, number> | null): string | null {
  const entries = Object.entries(fillerWords ?? {});
  if (!entries.length) return null;
  return `Filler words: ${entries.map(([word, count]) => `"${word}" (${count})`).join(', ')}`;
}

function getTurnDetailLines(turn: TranscriptTurn): string[] {
  if (!isCandidateTurn(turn)) return [];

  const lines: string[] = [];
  if (turn.feedback) {
    if (turn.feedback.star) {
      const star = (['situation', 'task', 'action', 'result'] as const)
        .map(key => `${key.charAt(0).toUpperCase() + key.slice(1)}: ${turn.feedback!.star![key] ? 'yes' : 'no'}`)
        .join(' | ');
      lines.push(`STAR: ${star}`);
    } else if (turn.feedback.technical) {
      const technical = (['accuracy', 'tradeoffs', 'depth'] as const)
        .map(key => `${key.charAt(0).toUpperCase() + key.slice(1)}: ${turn.feedback!.technical![key] ? 'yes' : 'no'}`)
        .join(' | ');
      lines.push(`Technical: ${technical}`);
    }

    if (turn.feedback.strengths.length > 0) {
      lines.push('Strengths:');
      turn.feedback.strengths.forEach(item => lines.push(`- ${item}`));
    }

    if (turn.feedback.improvements.length > 0) {
      lines.push('Areas to improve:');
      turn.feedback.improvements.forEach(item => lines.push(`- ${item}`));
    }
  }

  const fillerLine = formatFillerWords(turn.fillerWords);
  if (fillerLine) lines.push(fillerLine);

  return lines;
}

export function InterviewResults() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isDemo = user?.email === 'demo123@resumeapp.com';
  // The shared demo account views the canned showcase session; it has no real
  // sessions (interview start is sign-up gated), so this never shadows one.
  const isSampleSession = isDemo && sessionId === SAMPLE_INTERVIEW_SESSION_ID;
  const [signupPrompt, setSignupPrompt] = useState<{ title: string; body: string } | null>(null);
  const pendingFinalization = sessionId ? loadPendingInterviewFinalization(sessionId) : null;
  const [retryAssessmentCount, setRetryAssessmentCount] = useState(0);
  const shouldFinalizeInterview = Boolean(pendingFinalization);
  const finalizationEndReason = pendingFinalization?.endReason || 'user_ended';
  const finalizeStartedRef = useRef(false);
  const [session, setSession] = useState<SessionResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [finalizing, setFinalizing] = useState(shouldFinalizeInterview);
  const [error, setError] = useState('');
  const [restartError, setRestartError] = useState('');
  const [restarting, setRestarting] = useState(false);
  const [jobDescriptionOpen, setJobDescriptionOpen] = useState(false);
  const [transcriptOpen, setTranscriptOpen] = useState(true);
  const [activeTab, setActiveTab] = useState<'assessment' | 'transcript'>('assessment');
  const [disclaimerOpen, setDisclaimerOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const copiedTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const tabsRef = useRef<HTMLDivElement>(null);
  const pendingTabScrollRef = useRef(false);

  useEffect(() => {
    if (!sessionId) return;
    if (isSampleSession) {
      setSession(SAMPLE_INTERVIEW_SESSION);
      setLoading(false);
      setFinalizing(false);
      return;
    }
    const activeSessionId = sessionId;

    let cancelled = false;
    let pollTimeout: ReturnType<typeof setTimeout> | undefined;

    async function fetchSession() {
      const nextSession = await getSession(activeSessionId);
      if (!cancelled) {
        setSession(nextSession);
        setLoading(false);
      }
      return nextSession;
    }

    async function pollForAssessment(attempt = 0) {
      try {
        const nextSession = await fetchSession();
        const assessmentReady = Boolean(nextSession.assessment);
        const stillFinalizing = nextSession.status === 'active' || !assessmentReady;

        if (!cancelled && stillFinalizing && attempt < ASSESSMENT_POLL_MAX_ATTEMPTS) {
          pollTimeout = setTimeout(() => {
            void pollForAssessment(attempt + 1);
          }, ASSESSMENT_POLL_INTERVAL_MS);
          return;
        }

        if (!cancelled) {
          clearPendingInterviewFinalization(activeSessionId);
          setFinalizing(false);
        }
      } catch (err) {
        console.error('Failed to refresh interview results:', err);
        if (!cancelled) {
          setError('Failed to load interview results');
          setLoading(false);
          setFinalizing(false);
        }
      }
    }

    // /interview/end generates the assessment synchronously on the backend. The REST API
    // Gateway integration timeout (~29s) is shorter than the Lambda timeout (60s), so a slow
    // assessment returns 504 to the browser even though the Lambda keeps running and persists
    // the result — the pollForAssessment() fallback below recovers it, so the 504 is cosmetic
    // (console noise only). As of 2026-06-01, Lambda durations were avg ~20s / max ~33s, well
    // under 60s, so this is intentionally left as-is. TRIPWIRE: if Lambda max duration climbs to
    // ~45-50s (headroom to the 60s ceiling under ~10-15s), or real "couldn't generate" failures
    // appear in prod, migrate /interview/end to async (return 202 + finalizing/failed status,
    // poll getSession until completed) instead of generating inline.
    async function finalizeInterviewReport(attempt = 1) {
      try {
        const endResponse = await endInterview({
          sessionId: activeSessionId,
          endReason: finalizationEndReason,
        });
        if (cancelled) return;

        const nextSession = await fetchSession();
        const assessmentReady = Boolean(endResponse.assessment || nextSession.assessment);
        if (endResponse.assessment && !nextSession.assessment && !cancelled) {
          setSession({
            ...nextSession,
            status: 'completed',
            conversation: endResponse.conversation,
            totalDuration: endResponse.totalDuration,
            questionCount: endResponse.questionCount,
            assessment: endResponse.assessment,
          });
        }

        if (assessmentReady) {
          clearPendingInterviewFinalization(activeSessionId);
          setFinalizing(false);
          return;
        }

        if (attempt < ASSESSMENT_END_MAX_ATTEMPTS) {
          pollTimeout = setTimeout(() => {
            void finalizeInterviewReport(attempt + 1);
          }, ASSESSMENT_END_RETRY_DELAY_MS);
          return;
        }

        pollTimeout = setTimeout(() => {
          void pollForAssessment();
        }, 1000);
      } catch (err) {
        console.error('Failed to finalize interview:', err);
        if (!cancelled) {
          pollTimeout = setTimeout(() => {
            void pollForAssessment();
          }, 1000);
        }
      }
    }

    async function loadResults() {
      setError('');

      try {
        if (shouldFinalizeInterview && !finalizeStartedRef.current) {
          finalizeStartedRef.current = true;
          setFinalizing(true);
          await finalizeInterviewReport();
          return;
        }

        const initialSession = await fetchSession();
        if (initialSession.assessment) {
          clearPendingInterviewFinalization(activeSessionId);
        }
        if (shouldFinalizeInterview && !initialSession.assessment) {
          setFinalizing(true);
          pollTimeout = setTimeout(() => {
            void pollForAssessment();
          }, 1000);
        } else {
          setFinalizing(false);
        }
      } catch (err) {
        console.error('Failed to load interview results:', err);
        if (!cancelled) {
          setError('Failed to load interview results');
          setLoading(false);
          setFinalizing(false);
        }
      }
    }

    void loadResults();

    return () => {
      cancelled = true;
      if (pollTimeout) clearTimeout(pollTimeout);
    };
  }, [sessionId, isSampleSession, shouldFinalizeInterview, finalizationEndReason, retryAssessmentCount]);

  useEffect(() => {
    return () => {
      if (copiedTimerRef.current) clearTimeout(copiedTimerRef.current);
    };
  }, []);

  // Runs after the panel swap is committed — scrolling in the click handler would
  // target a panel that isn't in the DOM yet.
  useEffect(() => {
    if (!pendingTabScrollRef.current) return;
    pendingTabScrollRef.current = false;
    const tabs = tabsRef.current;
    const panel = document.getElementById(`ir-panel-${activeTab}`);
    if (!tabs || !panel) return;
    // Measure the sticky chrome rather than hardcoding it: the tab bar's height
    // moves with font size and zoom, and --app-header-h grows when the demo
    // banner is up. Guessing here buries the panel's heading under the bar.
    const headerHeight = parseFloat(getComputedStyle(tabs).top) || 0;
    const target = window.scrollY + panel.getBoundingClientRect().top
      - headerHeight - tabs.offsetHeight - TAB_SCROLL_GAP;
    const reduceMotion = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    window.scrollTo({ top: Math.max(0, target), behavior: reduceMotion ? 'auto' : 'smooth' });
  }, [activeTab]);

  if (loading) {
    return (
      <div className="page-container ir-page">
        <div className="ir-loading">
          <div className="loading-spinner" />
          <p className="text-secondary">
            {finalizing ? 'Finalizing your interview report...' : 'Loading interview results...'}
          </p>
        </div>
      </div>
    );
  }

  if (error || !session) {
    return (
      <div className="page-container ir-page">
        <div className="ir-error">
          <h2>Something went wrong</h2>
          <p className="text-secondary">{error || 'Session not found'}</p>
          <button className="btn btn-primary" onClick={() => navigate(-1)}>Go Back</button>
        </div>
      </div>
    );
  }

  const assessment = session.assessment;
  // Null-safe: a malformed/legacy session row could lack a conversation array.
  // Default to [] so the page renders an empty-transcript state instead of crashing.
  const conversation = session.conversation ?? [];
  const transcriptGroups = groupTranscript(conversation);
  const hasCategoryScores = (assessment?.categories.length ?? 0) > 0;
  const questionCount = conversation.filter(isInterviewQuestionTurn).length;
  const transcriptQuestionLabel = questionCount === 1 ? '1 question' : `${questionCount} questions`;
  const interviewType = formatInterviewType(session.interviewType);
  const typeBadge = `${interviewType} Interview`;
  const heading = getSessionHeading(session);
  const matchLabel = formatMatchScore(session.matchScore);
  const matchValue = parseMatchScore(session.matchScore);
  const matchTier = matchValue != null ? getMatchScoreTier(matchValue) : null;
  const hasContextLinks = Boolean(session.analysisId || session.jobDescription);
  const contextTitle = session.analysisId ? 'Analysis & Context' : 'Context';
  const isActiveSession = session.status === 'active';

  function downloadReport() {
    const lines: string[] = [
      '# Mock Interview Report',
      '',
      `Date: ${session!.createdAt ? new Date(session!.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}`,
      `Role: ${getSessionTitle(session!)}`,
      `Resume: ${getResumeLabel(session!)}`,
      ...(matchLabel ? [`Match: ${matchLabel}`] : []),
      `Duration: ${formatDuration(session!.totalDuration)}`,
      `Questions: ${questionCount}`,
      `Type: ${typeBadge}`,
      '',
      '---',
      '',
    ];
    if (assessment) {
      lines.push(`## Assessment: ${assessment.overallScore}% — ${assessment.overallRating}`);
      lines.push('');
      lines.push(assessment.summary);
      lines.push('');
      assessment.categories.forEach(cat => {
        lines.push(`### ${cat.name} — ${cat.score}%`);
        lines.push(cat.comment);
        lines.push('');
      });
      if (assessment.strengths.length) {
        lines.push('## Strengths');
        assessment.strengths.forEach(s => lines.push(`- ${s}`));
        lines.push('');
      }
      if (assessment.improvements.length) {
        lines.push('## Areas to Improve');
        assessment.improvements.forEach(s => lines.push(`- ${s}`));
        lines.push('');
      }
      lines.push('---');
      lines.push('');
    }
    lines.push('## Transcript');
    lines.push('');
    conversation.forEach((turn) => {
      lines.push(`**${getTranscriptLabel(turn, true)}**`);
      lines.push(turn.content);
      const detailLines = getTurnDetailLines(turn);
      if (detailLines.length > 0) {
        lines.push('');
        lines.push(...detailLines);
      }
      lines.push('');
    });
    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `interview-report-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  function copyTranscript() {
    const lines = conversation.flatMap((turn) => {
      return [`${getTranscriptLabel(turn)}: ${turn.content}`];
    });
    navigator.clipboard.writeText(lines.join('\n\n'));
    setCopied(true);
    if (copiedTimerRef.current) clearTimeout(copiedTimerRef.current);
    copiedTimerRef.current = setTimeout(() => setCopied(false), COPIED_RESET_MS);
  }

  async function startInterviewAgain() {
    if (isDemo) {
      setSignupPrompt({
        title: 'Start Your Mock Interview',
        body: 'Create a free account to practice role-specific interview questions and get a detailed interview report.',
      });
      return;
    }
    if (!session?.analysisId) return;

    setRestartError('');
    setRestarting(true);

    try {
      const analysis = await getAnalysis(session.analysisId);
      const resumeText = analysis.originalText || analysis.suggestedText || '';
      const jobDescription = analysis.jobDescription || session.jobDescription || '';

      if (!resumeText.trim() || !jobDescription.trim()) {
        setRestartError('Could not find the resume and job description for this session.');
        return;
      }

      clearInterviewPointer(resumeText, jobDescription);
      navigate('/interview', {
        state: {
          resumeText,
          jobDescription,
          fileName: analysis.fileName || session.fileName,
          analysisId: session.analysisId,
          jobTitle: analysis.jobTitle || getJobTitle(session),
          matchScore: analysis.matchScore ?? (typeof session.matchScore === 'number' ? session.matchScore : undefined),
          interviewType: getInterviewType(session.interviewType),
        },
      });
    } catch (err) {
      console.error('Failed to restart interview:', err);
      setRestartError('Could not prepare a new interview. Try opening the analysis and starting from there.');
    } finally {
      setRestarting(false);
    }
  }

  function retryAssessment() {
    if (!sessionId) return;
    savePendingInterviewFinalization(sessionId, finalizationEndReason);
    finalizeStartedRef.current = false;
    setError('');
    setFinalizing(true);
    setRetryAssessmentCount(count => count + 1);
  }

  function continueInterview() {
    if (!session) return;
    const numericMatchScore = typeof session.matchScore === 'number'
      ? session.matchScore
      : Number(session.matchScore);

    navigate('/interview', {
      state: {
        resumeSessionId: session.sessionId,
        fileName: session.fileName,
        analysisId: session.analysisId,
        jobTitle: getJobTitle(session) || getSessionTitle(session),
        matchScore: Number.isFinite(numericMatchScore) ? numericMatchScore : undefined,
        interviewType: getInterviewType(session.interviewType),
      },
    });
  }

  function selectTab(tab: 'assessment' | 'transcript') {
    if (tab === activeTab) return;
    // Both panels are long. Switching while scrolled deep into one would leave the
    // reader stranded in the middle of the other, so the effect below pulls the
    // incoming panel up under the tab bar — but only when they've already scrolled
    // past it. While the bar is still in its natural position the reader is near
    // the top anyway, and scrolling would push the session header out of view for
    // no reason. Measured here, before the swap, because it describes where the
    // reader *was*.
    const tabs = tabsRef.current;
    const stickyTop = tabs ? parseFloat(getComputedStyle(tabs).top) || 0 : 0;
    pendingTabScrollRef.current = Boolean(tabs) && tabs!.getBoundingClientRect().top <= stickyTop + 1;
    setActiveTab(tab);
  }

  return (
    <div className="page-container ir-page">
      <Link to="/interview/history" className="ir-back">
        <svg width="13" height="13" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M10 4l-4 4 4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
        </svg>
        Back to interviews
      </Link>

      <header className="ir-head animate-in">
        <div className="ir-head__title-row">
          <h1 className="ir-head__title">
            {heading.role}
            {heading.company && (
              <>
                {' '}
                <span className="ir-head__dash">—</span> {heading.company}
              </>
            )}
          </h1>
          {matchLabel && (
            <span className={`ir-head__match${matchTier ? ` ir-head__match--${matchTier}` : ''}`}>
              {matchLabel}
            </span>
          )}
        </div>

        <div className="ir-head__meta">
          <span className="ir-head__file">{getResumeLabel(session)}</span>
          <span className="ir-head__dot">&middot;</span>
          <span className="ir-head__stamp">{formatDate(session.createdAt)} &middot; {formatTime(session.createdAt)}</span>
          <span className="ir-head__dot">&middot;</span>
          <span className="ir-head__type">{interviewType}</span>
          <span className="ir-head__stamp">{transcriptQuestionLabel}</span>
        </div>

        <div className="ir-actions">
          {isActiveSession ? (
            <button type="button" className="ir-btn ir-btn--primary" onClick={continueInterview}>
              Continue Interview
            </button>
          ) : session.analysisId && (
            <button
              type="button"
              className="ir-btn ir-btn--primary"
              onClick={startInterviewAgain}
              disabled={restarting}
            >
              <svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true">
                <path d="M2.5 8a5.5 5.5 0 1 1 1.6 3.9M2.5 12v-3h3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
              </svg>
              {restarting ? 'Preparing...' : 'Interview again'}
            </button>
          )}
          <button type="button" className="ir-btn" onClick={downloadReport}>
            <svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true">
              <path d="M8 2v8M5 7l3 3 3-3M3 13h10" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" fill="none" />
            </svg>
            Interview report
          </button>
          <button type="button" className="ir-btn" onClick={copyTranscript}>
            <svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true">
              <rect x="5" y="5" width="8" height="9" rx="1.5" stroke="currentColor" strokeWidth="1.3" fill="none" />
              <path d="M11 5V3.5A1.5 1.5 0 0 0 9.5 2H4a1.5 1.5 0 0 0-1.5 1.5V10" stroke="currentColor" strokeWidth="1.3" fill="none" />
            </svg>
            {copied ? 'Copied' : 'Copy transcript'}
          </button>
        </div>
        {restartError && <p className="ir-actions__error">{restartError}</p>}
      </header>

      {hasContextLinks && (
        <section className="ir-context animate-in stagger-1">
          <div className="ir-context__title">{contextTitle}</div>
          <div className="ir-context__actions">
            {session.analysisId && (
              <Link className="ir-btn ir-btn--sm" to={`/results/${session.analysisId}`}>
                <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
                  <path d="M4 2h6l3 3v9H4V2Z" stroke="currentColor" strokeWidth="1.3" fill="none" strokeLinejoin="round" />
                  <path d="M10 2v3h3" stroke="currentColor" strokeWidth="1.3" fill="none" />
                </svg>
                View full analysis
                <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
                  <path d="M5 11L11 5M6 5h5v5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                </svg>
              </Link>
            )}
            {session.jobDescription && (
              <button
                type="button"
                className="ir-btn ir-btn--sm"
                aria-expanded={jobDescriptionOpen}
                onClick={() => setJobDescriptionOpen(open => !open)}
              >
                Job description
                <span className={`ir-chevron${jobDescriptionOpen ? ' ir-chevron--open' : ''}`}>
                  <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
                    <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                  </svg>
                </span>
              </button>
            )}
          </div>
          {jobDescriptionOpen && session.jobDescription && (
            <div className="ir-context__jd">{session.jobDescription}</div>
          )}
        </section>
      )}

      <div className="ir-tabs animate-in stagger-1" ref={tabsRef}>
        <div className="ir-tabs__group" role="tablist" aria-label="Interview report sections">
          <button
            type="button"
            role="tab"
            id="ir-tab-assessment"
            aria-controls="ir-panel-assessment"
            aria-selected={activeTab === 'assessment'}
            className={`ir-tab${activeTab === 'assessment' ? ' ir-tab--active' : ''}`}
            onClick={() => selectTab('assessment')}
          >
            <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
              <path d="M3 13V7M7 13V3M11 13V9" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
            Assessment
          </button>
          <button
            type="button"
            role="tab"
            id="ir-tab-transcript"
            aria-controls="ir-panel-transcript"
            aria-selected={activeTab === 'transcript'}
            className={`ir-tab${activeTab === 'transcript' ? ' ir-tab--active' : ''}`}
            onClick={() => selectTab('transcript')}
          >
            <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
              <path d="M3 4h10M3 8h10M3 12h6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
            Transcript
          </button>
        </div>
      </div>

      {activeTab === 'assessment' && (
        assessment ? (
          <section id="ir-panel-assessment" role="tabpanel" aria-labelledby="ir-tab-assessment" className="ir-assessment animate-in stagger-2">
            <div className="ir-assessment__head">
              <h2>Assessment</h2>
              <span className="ir-ai-pill">
                <svg width="12" height="12" viewBox="0 0 16 16" aria-hidden="true">
                  <path d="M8 1.5l1.6 3.9 4.2.3-3.2 2.7 1 4.1L8 10.9 4.4 12.6l1-4.1L2.2 5.7l4.2-.3L8 1.5Z" fill="currentColor" />
                </svg>
                AI-generated
              </span>
              <button
                type="button"
                className="ir-details-toggle"
                aria-expanded={disclaimerOpen}
                onClick={() => setDisclaimerOpen(open => !open)}
              >
                {disclaimerOpen ? 'Hide details' : 'Show details'}
              </button>
            </div>

            {disclaimerOpen && (
              <div className="ir-details-callout" role="note">
                {ASSESSMENT_RUBRIC_COPY[getInterviewType(session.interviewType)]}
              </div>
            )}

            {assessment.clarityAdjusted && assessment.transcriptClarityStats && (
              <div className="ir-clarity-banner" role="note">
                <span className="ir-clarity-banner__icon" aria-hidden="true">i</span>
                <span>
                  This score was adjusted because{' '}
                  {assessment.transcriptClarityStats.unclearTurnCount} of{' '}
                  {assessment.transcriptClarityStats.candidateTurnCount} answers had
                  transcription errors. Your communication score reflects this.
                </span>
              </div>
            )}

            <section className="ir-panel ir-overall">
              <div className="ir-panel__title">Overall Score</div>
              <div className="ir-overall__body">
                {hasCategoryScores && (
                  <div className="ir-overall__ring">
                    <svg width="132" height="132" viewBox="0 0 132 132">
                      <circle cx="66" cy="66" r="56" fill="none" stroke="var(--track)" strokeWidth="11" />
                      <circle
                        cx="66" cy="66" r="56" fill="none"
                        stroke={scoreColor(assessment.overallScore)}
                        strokeWidth="11" strokeLinecap="round"
                        strokeDasharray={`${(assessment.overallScore / 100) * 351.9} 351.9`}
                        transform="rotate(-90 66 66)"
                      />
                    </svg>
                    <span className="ir-overall__value">{assessment.overallScore}%</span>
                  </div>
                )}
                <div>
                  <div
                    className="ir-overall__band"
                    style={hasCategoryScores ? { color: scoreColor(assessment.overallScore) } : undefined}
                  >
                    {hasCategoryScores ? assessment.overallRating : 'Assessment incomplete'}
                  </div>
                  <div className="ir-overall__hint">
                    {hasCategoryScores
                      ? `${assessment.overallScore}% overall across ${assessment.categories.length} scoring categories`
                      : 'No category scores were generated for this session.'}
                  </div>
                </div>
              </div>
            </section>

            {hasCategoryScores && (
              <div className="ir-cat-grid" aria-label="Dimension scores">
                {assessment.categories.map((cat, i) => (
                  <div key={i} className="ir-cat">
                    <div className="ir-cat__score" style={{ color: scoreColor(cat.score) }}>{cat.score}%</div>
                    <div className="ir-cat__name">{cat.name}</div>
                    <div className="ir-cat__weight">weight {formatCategoryWeight(cat.weight)}%</div>
                  </div>
                ))}
              </div>
            )}

            <section className="ir-panel ir-summary">
              <h3>Assessment Summary</h3>
              <p className="ir-summary__text">{assessment.summary}</p>
              {assessment.improvements.length > 0 && (
                <div className="ir-summary__highlights">
                  {assessment.improvements.map((item, i) => (
                    <div key={i} className="ir-summary__highlight">
                      <span className="ir-summary__mark">+</span>
                      <p>{item}</p>
                    </div>
                  ))}
                </div>
              )}
            </section>

            <div className="ir-feedback">
              <section className="ir-panel ir-feedback__col">
                <div className="ir-feedback__head">
                  <span className="ir-feedback__title">Strengths</span>
                  {assessment.strengths.length > 0 && (
                    <span className="ir-feedback__count">
                      {assessment.strengths.length} {assessment.strengths.length === 1 ? 'item' : 'items'}
                    </span>
                  )}
                </div>
                {assessment.strengths.length === 0 ? (
                  <p className="ir-feedback__empty">
                    Detailed strengths were not generated for this session.{' '}
                    {hasCategoryScores
                      ? 'Review the category scores and transcript feedback for more context.'
                      : 'Review the assessment summary and transcript feedback for more context.'}
                  </p>
                ) : (
                  <div className="ir-feedback__list">
                    {assessment.strengths.map((item, i) => (
                      <div key={i} className="ir-feedback__item ir-feedback__item--strength">
                        <svg width="16" height="16" viewBox="0 0 18 18" aria-hidden="true">
                          <circle cx="9" cy="9" r="7.5" stroke="var(--success-alt)" strokeWidth="1.4" fill="none" />
                          <polyline points="5.5,9 8,11.3 12.5,6.2" fill="none" stroke="var(--success-alt)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        <p>{item}</p>
                      </div>
                    ))}
                  </div>
                )}
              </section>

              <section className="ir-panel ir-feedback__col">
                <div className="ir-feedback__head">
                  <span className="ir-feedback__title">Areas to Improve</span>
                  {assessment.improvements.length > 0 && (
                    <span className="ir-feedback__count">
                      {assessment.improvements.length} {assessment.improvements.length === 1 ? 'item' : 'items'}
                    </span>
                  )}
                </div>
                {assessment.improvements.length === 0 ? (
                  <p className="ir-feedback__empty">
                    Detailed improvement notes were not generated for this session.{' '}
                    {hasCategoryScores
                      ? 'Review the category scores and transcript feedback for more context.'
                      : 'Review the assessment summary and transcript feedback for more context.'}
                  </p>
                ) : (
                  <div className="ir-feedback__list">
                    {assessment.improvements.map((item, i) => (
                      <div key={i} className="ir-feedback__item ir-feedback__item--improve">
                        <svg width="16" height="16" viewBox="0 0 18 18" aria-hidden="true">
                          <circle cx="9" cy="9" r="7.5" stroke="var(--warn)" strokeWidth="1.4" fill="none" />
                          <path d="M6 9h6M9.5 6.5L12 9l-2.5 2.5" stroke="var(--warn)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                        </svg>
                        <p>{item}</p>
                      </div>
                    ))}
                  </div>
                )}
              </section>
            </div>

            {hasCategoryScores && (
              <section className="ir-panel ir-dimensions">
                <h3>Detailed Dimension Feedback</h3>
                <div className="ir-dimensions__list">
                  {assessment.categories.map((cat, i) => (
                    <div key={i} className="ir-dimension">
                      <div className="ir-dimension__meta">
                        <div className="ir-dimension__head">
                          <span className="ir-dimension__name">{cat.name}</span>
                          <span className="ir-dimension__score" style={{ color: scoreColor(cat.score) }}>
                            {cat.score}%
                          </span>
                        </div>
                        <div className="ir-dimension__bar">
                          <div
                            className="ir-dimension__fill"
                            style={{ width: `${cat.score}%`, background: scoreColor(cat.score) }}
                          />
                        </div>
                        <div className="ir-dimension__weight">
                          Weight {formatCategoryWeight(cat.weight)}% of overall
                        </div>
                      </div>
                      <p className="ir-dimension__comment">{cat.comment}</p>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </section>
        ) : (
          <section id="ir-panel-assessment" role="tabpanel" aria-labelledby="ir-tab-assessment" className="ir-assessment animate-in stagger-2">
            <div className="ir-assessment__head">
              <h2>Assessment</h2>
            </div>
            {finalizing ? (
              <div className="ir-panel ir-state-banner" role="status" aria-live="polite">
                <div className="loading-spinner ir-state-banner__spinner" />
                <div className="ir-state-banner__body">
                  <h3>Finalizing your interview report</h3>
                  <p>Transcript is ready. Analyzing responses and generating feedback...</p>
                  <span>Usually takes ~10-20 seconds</span>
                </div>
              </div>
            ) : (
              <div className="ir-panel ir-state-banner ir-state-banner--error" role="status">
                <div className="ir-state-banner__icon" aria-hidden="true">
                  <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
                    <path d="M12 8v5M12 17h.01M10.3 4.3 2.6 18a1.5 1.5 0 0 0 1.3 2.2h16.2a1.5 1.5 0 0 0 1.3-2.2L13.7 4.3a1.9 1.9 0 0 0-3.4 0Z" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                <div className="ir-state-banner__body">
                  <h3>We couldn&apos;t generate your assessment</h3>
                  <p>You can review your responses or try again.</p>
                  <div className="ir-state-banner__actions">
                    <button type="button" className="ir-btn ir-btn--primary" onClick={retryAssessment}>
                      Retry assessment
                    </button>
                    {session.analysisId && (
                      <button
                        type="button"
                        className="ir-btn"
                        onClick={startInterviewAgain}
                        disabled={restarting}
                      >
                        {restarting ? 'Preparing...' : 'Start new interview'}
                      </button>
                    )}
                  </div>
                </div>
              </div>
            )}
          </section>
        )
      )}

      {activeTab === 'transcript' && (
        <section id="ir-panel-transcript" role="tabpanel" aria-labelledby="ir-tab-transcript" className="ir-panel ir-transcript animate-in stagger-2">
          <button
            type="button"
            className="ir-transcript__toggle"
            aria-expanded={transcriptOpen}
            onClick={() => setTranscriptOpen(open => !open)}
          >
            <span className="ir-transcript__heading">
              <span className="ir-transcript__title">Session Transcript</span>
              <span className="ir-transcript__count">{transcriptQuestionLabel}</span>
            </span>
            <span className={`ir-chevron${transcriptOpen ? ' ir-chevron--open' : ''}`}>
              <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
                <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" fill="none" />
              </svg>
            </span>
          </button>

          {transcriptOpen && (
            <div className="ir-transcript__body">
              <div className="ir-transcript__inner">
                {transcriptGroups.length === 0 && (
                  <p className="ir-transcript__empty">No transcript available for this session.</p>
                )}
                {transcriptGroups.map((group, i) => (
                  <div key={i} className="ir-turn">
                    {group.question && (
                      <>
                        <div className="ir-turn__label ir-turn__label--interviewer">INTERVIEWER</div>
                        <div className="ir-turn__question">{group.question.content}</div>
                      </>
                    )}
                    {group.answers.length > 0 && (
                      <>
                        <div className="ir-turn__label">YOU</div>
                        {group.answers.map((answer, j) => (
                          <div key={j} className="ir-turn__answer">
                            <div className="ir-turn__paragraphs">
                              {toParagraphs(answer.content).map((paragraph, k) => (
                                <p key={k}>{paragraph}</p>
                              ))}
                            </div>
                            {answer.transcriptClarity === 'unclear' && (
                              <div className="ir-clarity-warning" role="note">
                                <span className="ir-clarity-warning__icon" aria-hidden="true">!</span>
                                <span>Low audio quality (transcription may be imperfect).</span>
                              </div>
                            )}
                            {answer.feedback && (
                              <FeedbackBlock feedback={answer.feedback} fillerWords={answer.fillerWords} />
                            )}
                            {!answer.feedback && answer.fillerWords && Object.keys(answer.fillerWords).length > 0 && (
                              <div className="ir-fillers">{formatFillerWords(answer.fillerWords)}</div>
                            )}
                          </div>
                        ))}
                      </>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </section>
      )}

      {signupPrompt && (
        <SignupPromptModal
          onClose={() => setSignupPrompt(null)}
          title={signupPrompt.title}
          body={signupPrompt.body}
        />
      )}
    </div>
  );
}

const STAR_KEYS = ['situation', 'task', 'action', 'result'] as const;
const TECHNICAL_KEYS = ['accuracy', 'tradeoffs', 'depth'] as const;

function FeedbackBlock({ feedback, fillerWords }: { feedback: TurnFeedback; fillerWords?: Record<string, number> | null }) {
  const rubric = feedback.star
    ? STAR_KEYS.map(key => ({ key, name: key.charAt(0).toUpperCase() + key.slice(1), passed: feedback.star![key] }))
    : feedback.technical
      ? TECHNICAL_KEYS.map(key => ({ key, name: key.charAt(0).toUpperCase() + key.slice(1), passed: feedback.technical![key] }))
      : [];
  const fillerLine = formatFillerWords(fillerWords);

  return (
    <div className="ir-turn__feedback">
      {rubric.length > 0 && (
        <div className="ir-rubric">
          {rubric.map(item => (
            <span
              key={item.key}
              className={`ir-rubric__item${item.passed ? ' ir-rubric__item--pass' : ''}`}
            >
              <span className="ir-rubric__mark">{item.passed ? '✓' : '✗'}</span>
              {item.name}
            </span>
          ))}
        </div>
      )}
      {(feedback.strengths.length > 0 || feedback.improvements.length > 0 || fillerLine) && (
        <div className="ir-notes">
          {feedback.strengths.map((item, i) => (
            <div key={`s${i}`} className="ir-note">
              <span className="ir-note__mark ir-note__mark--plus">+</span>
              <span className="ir-note__text">{item}</span>
            </div>
          ))}
          {feedback.improvements.map((item, i) => (
            <div key={`i${i}`} className="ir-note ir-note--improve">
              <span className="ir-note__mark ir-note__mark--arrow">&rarr;</span>
              <span className="ir-note__text">{item}</span>
            </div>
          ))}
          {fillerLine && <div className="ir-fillers">{fillerLine}</div>}
        </div>
      )}
    </div>
  );
}
